### ISSUE TITLE
No Filter.XXXX in calibration

### ISSUE THREAD

**Issue by lucas95123** [tomas789/tonav#5]
Hi! I've been interested in running tonav for testing, I've done the all the compiling but when I run the program, it throws an exception:
<pre>
terminate called after throwing an instance of 'CalibrationFileError'
  what():  Parameter Filter.maxCameraPoses not set in configuration file.
Aborted (core dumped)
</pre>
I used the calibration.yaml in the supplementary files but it seems that there are some option missing,

**Comment by tomas789** [comment]
Hi. Thank you for your interest in this repository. I've created a gist where I put configuration that I use for development purpose. Please keep in mind that there is a lot of parameters that you have to adjust to your dataset and also mind, that Tonav is still work in progress.

**Comment by lucas95123** [comment]
Thx for your help :), I still have one question left, since I'm new to ros, I can't quiet figure out how to load the .bag file as the input data. I ran roscore on one terminal and ./tonav-master in another but nothing happens.

**Comment by tomas789** [comment]
Just run `rosbag play <my-bag-file-name>`. If you have bag file publishing to correct topics, it will work. You can check list of bagfile published topics by running `rosbag info <my-bag-file-name>`. After you play your bag file, you can check real topics with command `rostopic list`.

**Comment by lucas95123** [comment]
It worked, thanks man, appreciate your help.
