### ISSUE TITLE
fatal error ：src/LevenbergMarquardt/LMqrsolv.h：No such file or directory

### ISSUE THREAD

**Issue by cheneyfan** [tomas789/tonav#7]
There is no LevenbergMarquardt folder in Eigen3， what‘s the version and config do you use？

**Comment by tomas789** [comment]
Hi, this is not part of Tonav. It is part of [Eigen library](https://eigen.tuxfamily.org/dox/unsupported/classEigen_1_1LevenbergMarquardt.html). What is your OS and version of Eigen?

**Comment by cheneyfan** [comment]
Ubuntu14.04 Eigen3

**Comment by tomas789** [comment]
First of all I'm sorry for this kind of a problems. I currently work hard to get it work smoothly. I distribute it publicly with no guarantees. 
I searched Ubuntu repositories and it looks like this file is missing in package [libeigen3-dev](http://packages.ubuntu.com/trusty/all/libeigen3-dev/filelist) but it is [part of official Eigen library](https://eigen.tuxfamily.org/dox/unsupported/LMqrsolv_8h_source.html) (maybe Ubuntu distributes older version or something). So try installing manually newest version of Eigen. It works for me. Please let me know how you got it working. Thanks.

**Comment by tomas789** [comment]
It looks like when you download version 3.2.0 from [official Eigen repository](https://bitbucket.org/eigen/eigen/downloads?tab=tags), which is the version Ubuntu 14.04 has, you get this file. So you have no other option then install it manually.

**Comment by cheneyfan** [comment]
manually install eigen 3.2.0?

**Comment by tomas789** [comment]
Try installing latest version available, which is 3.3.1 at the moment.

**Comment by cheneyfan** [comment]
i have eigen under  /usr/include and /usr/local/include at the same time，so how to choose to use local one？

**Comment by tomas789** [comment]
I use 3rd party [FindEigen3.cmake](https://github.com/tomas789/tonav/blob/master/cmake/FindEigen3.cmake) module. You can look there for more hints. Environment variables `EIGEN3_ROOT` and `EIGEN3_ROOT_DIR` should do the trick but I've never tried it.
You can also consider uninstalling the other Eigen version.

**Comment by cheneyfan** [comment]
how to get image ，camerainfo and imu from .bag？

**Comment by cheneyfan** [comment]
what’s the total cmd of the MIT example？
where is the specific folder “./tonav --image /wide_stereo/left/image_rect --camerainfo /wide_stereo/left/camera_info --imu /torso_lift_imu/data”？

if i need to run “roscore” then what's the whole cmd and under which folder to input the cmd.

it seems not friendly

**Comment by tomas789** [comment]
Well, I understand your confusion. ROS isn't the simplest thing to start with. I recomand starting with [ROS tutorials](http://wiki.ros.org/ROS/Tutorials). You will get familiar with concepts of nodes and topics (which is how you get images, IMU and so on). Then in part 17 you can see how to play .bag files.

**Comment by cheneyfan** [comment]
Good！it works！

**Comment by OsgoodWu** [comment]
hello tomas,
when i run your program using “./tonav --image /wide_stereo/left/image_rect --camerainfo /wide_stereo/left/camera_info --imu /torso_lift_imu/data”,errors occured,i would like to know robot_base_link and twist can be set for what?thank you

**Comment by OsgoodWu** [comment]
hi,cheneyfan,
may i ask you how to run tomas' program using "./tonav --image /wide_stereo/left/image_rect --camerainfo /wide_stereo/left/camera_info --imu /torso_lift_imu/data",i found some parameters are missing like "robot_base_link" and "twist"?
