### ISSUE TITLE
Bugs report

### ISSUE THREAD

**Issue by linpenghong** [tomas789/tonav#9]
Hi Tomas, 
In function "CameraAlgorithms::cameraProjectJacobian"
dr_by_xyz not need to add Eigen::RowVector3d::Constant(1.0).

**Comment by tomas789** [comment]
You are right. Thank you. I will fix it.

**Comment by tomas789** [comment]
It looks like you paid close attention to source code of Tonav. Could you please share with me few insights with me? I'm very curious how you plan to use it. Are you planning to use it for any particular purpose? Have you already try it in your setup? How did it work? I'd appreciate if you tell me more. Either write me here or to my email tomas789@gmail.com. Thank you very much.

**Comment by linpenghong** [comment]
Hey Tomas,
I found Tonav is  a great work for the implementation of MSCKF, though I haven't got it worked right now. Actually I want to use MSCKF to filter the multi-sensor data from BDS（BeiDou Navigation Satellite System）， camera and IMU. I'm trying to check or rewrite the Tonav part by part to find bugs according Shelly's paper. I want to know while there is a version that worked for MIT Stata Center Data Set or some other opening data set? BTW, I found that README.md is not the match for the newest version.

**Comment by jian-li** [comment]
Hey linpengong, I was also writing msckf referering to shelley! There are two equation errors in shelly's paper, the first one is (6.44), the Nc should multiple 0.5f * delta_t ,the second is the chi-square test, in liminyang's paper it is mahanobis gating-test. I tested the chi-square test, it seldom have points passed the test!
